export const content = `
<div class='doc-lead'>
  <p>
    ClientPortal is a free white-label client portal software for agencies and service businesses
    that eliminates the scattered email threads, Dropbox folder links, and manual status updates
    that define most client communication workflows. Platforms like HoneyBook ($16-150/month),
    Dubsado ($20-40/month), Copilot ($39-99/month), and 17hats ($45/month) solve part of this
    problem but require clients to create accounts and agencies to pay substantial monthly fees.
    ClientPortal gives each client a branded, password-free portal where they can review
    deliverables, request changes, track project milestones, communicate through threaded messages,
    and access invoices — all under your agency's logo and colors. This documentation covers
    how to set up a branded portal, share files, request client approvals, connect invoicing,
    and configure access settings for each project.
  </p>
</div>

<h2>Getting Started with ClientPortal</h2>
<ol class='doc-steps'>
  <li>
    <strong>Set up your agency branding.</strong> In Settings → Brand, upload your logo, set your
    primary brand color, and enter the name that appears in portal headers and email notifications.
    ClientPortal uses these settings on every portal your clients see. Your clients experience a
    professionally branded environment, not a generic SaaS interface. If you manage multiple
    brands or sub-brands, create separate workspace profiles under the same account — each
    workspace has independent branding settings.
  </li>
  <li>
    <strong>Create a project and configure the portal.</strong> Click 'New Project,' enter the
    client name, project name, start date, and expected delivery date. Select which portal
    modules to enable for this project: File Sharing, Approval Requests, Messages, Invoice
    Tracker, and Project Timeline. Enable only the modules relevant to this engagement —
    a simple one-deliverable project might only need File Sharing and Approval Requests,
    while a long-term retainer might use all five. ClientPortal generates a unique portal URL
    for the project automatically.
  </li>
  <li>
    <strong>Add deliverables and set the project timeline.</strong> In the Timeline module, add
    the key project milestones visible to the client: kickoff, first draft, revision round,
    final delivery, and launch. Each milestone has a date and a status (upcoming, in progress,
    complete). As the project progresses, update milestone statuses — the client sees the
    timeline update in real time without you sending a separate status email. This single change
    eliminates the most common client question: 'Where are we on the project?'
  </li>
  <li>
    <strong>Share the portal link with your client.</strong> From the project overview, click
    'Share Portal.' Enter the client's email address — ClientPortal sends a branded invitation
    email with the portal link and a short explanation that no account creation is required.
    The client clicks the link and lands directly in their project portal. Optionally, set a
    link expiry date and a PIN access code for additional security on sensitive projects.
  </li>
  <li>
    <strong>Manage files, approvals, and messages from the project dashboard.</strong> Upload
    deliverables, request approvals, respond to client messages, and update invoice status
    from the project dashboard in your ClientPortal account. Everything the client does in
    the portal — downloading a file, approving a deliverable, sending a message — triggers
    a real-time notification on your dashboard. You never need to check email to stay on top
    of client activity.
  </li>
</ol>

<h2>Core Features</h2>

<h3>Branded Portal with Custom Logo and Colors</h3>
<p>
  Every client portal generated by ClientPortal carries your agency's logo, primary color,
  and business name. The portal header, email notifications, file download pages, and approval
  request screens all render in your brand. Clients see your name — not ClientPortal's — throughout
  every interaction. This matters for agency credibility: a professional branded portal signals
  operational maturity and reinforces the perception that you have invested in a proper client
  management system.
</p>
<p>
  Brand settings apply globally across all projects by default. For agencies serving clients
  in distinct industry verticals with separate brand identities, the workspace feature allows
  you to maintain up to five independent brand configurations under one account. Assign each
  new project to the appropriate workspace during setup, and the correct branding applies
  automatically to that client's portal.
</p>

<h3>File Sharing and Deliverable Uploads</h3>
<p>
  Upload any file type to the client portal: design files (PDF, PNG, JPG, SVG), documents
  (Word, Google Docs export, Excel), video files (MP4, MOV), zip archives, or raw source files.
  Files are organized by upload date and category label — you assign each file a category
  (Draft, Final, Reference, Contract) so the client can filter to what they need without
  scrolling through an unorganized list. File versions are tracked: uploading a revised version
  of an existing deliverable links the new file to the original, preserving the revision history
  in a single row rather than creating duplicate entries.
</p>
<p>
  ClientPortal logs every download event — the time, the file name, and the session. If a client
  claims they never received the final files, you have a timestamped record of every download.
  Large files (over 2GB) are supported through chunked upload with resume capability, so unstable
  connections do not require restarting an upload from scratch.
</p>

<h3>Client Approval Requests with Comments</h3>
<p>
  When a deliverable is ready for client review, send an approval request directly from the
  file in the portal. The client receives a notification (email and in-portal) that something
  is awaiting their review. In the portal, they see the file preview alongside two options:
  Approve or Request Changes. If they request changes, they must enter a comment describing
  what needs to be revised before the request submits. You receive the change request with
  their comment attached, revise the deliverable, upload the new version, and reopen the
  approval request.
</p>
<p>
  Every approval decision is timestamped and associated with a specific file version. The
  approval history panel shows the complete approval chain: when the request was sent, when
  it was opened, the decision, and any comments. For projects with multiple deliverables
  requiring approval, the Approvals dashboard shows the status of all outstanding and
  completed approvals across every file in the project.
</p>

<h3>Invoice and Payment Tracking Within the Portal</h3>
<p>
  Add invoices to the client portal from the Invoice module. Enter the invoice number, amount,
  due date, and a description. Clients see the invoice in their portal with a clear paid or
  unpaid status indicator. When payment is received — through your external payment processor,
  bank transfer, or check — mark the invoice as paid in ClientPortal. The status updates
  for the client immediately. This gives clients a central record of their financial relationship
  with your agency without requiring you to migrate to a full billing platform.
</p>
<p>
  For agencies using a separate invoicing tool, the Invoice module works as a tracker and
  communication layer rather than a billing system. Record the invoice reference number and
  link to your external invoice (a FreshBooks or InvoiceAI link, for example) from the invoice
  entry in ClientPortal. The client sees the record and can follow the link to pay through
  your existing payment flow. See also <a href='/blog/best-free-crm-small-business-2026'>managing
  client relationships guide</a> for connecting portal invoicing to broader client account tracking.
</p>

<h3>Project Status Timeline Visible to Clients</h3>
<p>
  The project timeline gives clients a visual overview of where their project stands without
  requiring them to email you for a status update. Add milestone names and target dates at
  project kickoff: Discovery, Concept Presentation, First Draft, Revision Round, Final Delivery,
  Launch. As each milestone is reached, mark it complete in ClientPortal — the timeline updates
  in the client's portal view instantly. Past milestones display a green checkmark; the current
  active milestone is highlighted; future milestones show their target dates.
</p>
<p>
  When a milestone is running late, update its date in the timeline and add an optional note
  explaining the change. The client sees the revised date and your note in the timeline row.
  Communicating a delay proactively through the portal — before the client notices the missed
  date and emails you — is a more professional handling than reactive explanation. Agencies
  that use the timeline consistently report a significant reduction in unsolicited client
  status-check emails.
</p>

<h3>Message Thread Per Project</h3>
<p>
  Each project has a dedicated message thread in ClientPortal where you and your client
  communicate about that specific project. Messages are displayed in chronological order,
  support rich text formatting, and allow file attachments up to 500MB. Because messages
  are project-scoped, you never have to search through a long email thread to find the
  specific conversation about file X or revision request Y — everything is in the portal,
  tied to the project context.
</p>
<p>
  You receive email notifications for every new client message with a direct link to reply
  in the portal. Clients receive the same when you reply. Both parties can choose to reply
  in the portal or via email — email replies are captured in the message thread automatically,
  so the conversation history is always complete regardless of where each person replied from.
</p>

<h3>Client Access Without Account Creation</h3>
<p>
  Clients access their portal via a unique link — no username, password, or account registration
  required. The link is generated per project and can be sent directly or embedded in your
  client onboarding email. Clients bookmark the link for repeat access. For projects requiring
  additional security, add an optional PIN that the client must enter before the portal loads.
  The PIN is set by you and communicated to the client separately from the portal link, so
  even if the link is forwarded to an unintended recipient, the portal content remains protected.
</p>
<p>
  Multiple client contacts at the same company can use the same portal link simultaneously —
  for example, the marketing manager and the CMO both reviewing a campaign deliverable. Each
  person's approval action is tracked individually based on the name they enter in the portal
  session. If you need strict per-person authentication, use the PIN feature with a unique
  PIN per contact.
</p>

<h3>Portal Link Expiry Settings</h3>
<p>
  Set an expiry date on any portal link from the project's Share settings. After the expiry
  date, the link shows an expired notice when visited — the portal content is not deleted,
  only the access link becomes inactive. Regenerate a new link at any time from the same
  settings panel and share it with the client to restore access. Use link expiry for projects
  with defined delivery dates — the portal access closes after final delivery, preventing
  clients from accessing old project materials after the engagement ends.
</p>
<p>
  For long-term retainer clients, leave the portal link without an expiry date so it functions
  as a permanent project communication hub. You can organize retainer portals by month or
  quarter — create a new project for each period and archive the prior period's portal when
  the work is complete. Archived portals are read-only: clients with the old link can view
  the history but cannot send new messages or submit new approval requests.
</p>

<h2>Common Use Cases</h2>

<h3>Design Agency Delivering Brand Identity Projects</h3>
<p>
  A brand design agency creates a ClientPortal project for every new identity engagement.
  At kickoff, the project manager builds the timeline with five milestones: Discovery, Mood
  Board, Logo Concepts (3 directions), Selected Direction Refinement, and Final Delivery.
  As the project progresses, the designer uploads deliverables to the portal with category
  labels — mood boards under Reference, logo concepts under Draft, and final files under Final.
  Each round of deliverables triggers an approval request. The client reviews in the portal,
  approves or requests changes with specific comments, and the designer iterates. By the time
  the project reaches final delivery, the portal contains a complete timestamped record of
  every version presented and every decision made — invaluable if scope creep or revision
  count disputes arise later.
</p>

<h3>Marketing Agency Managing Monthly Retainers</h3>
<p>
  A content marketing agency uses ClientPortal for 18 retainer clients simultaneously. Each
  client has a persistent portal where monthly content calendars, draft blog posts, social
  media assets, and performance reports are uploaded and approved. The message thread replaces
  back-and-forth email chains about individual pieces. At the start of each month, the agency
  uploads the content calendar to the portal and sends an approval request — the client approves
  or comments, and work begins. Monthly invoices are added to the Invoice module when sent and
  marked paid when cleared. Each client has a complete record of everything approved and invoiced
  in a single portal, making year-end client reviews straightforward.
</p>

<h3>Web Development Agency Managing a Site Launch</h3>
<p>
  A web development agency builds a project portal for a site launch engagement with multiple
  stakeholders at the client company. The portal timeline covers Discovery, Wireframes, Design
  Mockups, Development Build, UAT Review, and Launch. Design mockups require approval from the
  marketing director; the development build requires approval from the IT lead. The agency sends
  targeted approval requests to each stakeholder. The message thread keeps all communication
  project-scoped rather than spread across email chains between multiple people. When the IT lead
  requests a change to the hosting configuration, the conversation is recorded in the portal
  where the marketing director can also see it, eliminating the 'nobody told me' problem that
  delays launches. Learn more at <a href='/tools/client-portal'>ClientPortal</a>.
</p>

<div class='doc-tip'>
  <strong>Tip:</strong> Build your project timeline at kickoff — even if the dates change — and
  share it with the client before any work begins. Clients who see a timeline on day one ask
  fewer status-check questions throughout the project because they have a reference to consult
  themselves. Updating milestone statuses takes 30 seconds and saves multiple email exchanges.
</div>

<h2>Frequently Asked Questions</h2>

<div class='article-faq'>
  <div class='faq-item'>
    <h3>How do I set up a branded client portal?</h3>
    <p>
      Go to Settings → Brand in your ClientPortal account. Upload your logo in PNG or SVG format
      at a minimum 200px width for sharp rendering across screen sizes. Enter your business name
      as it should appear in portal headers and email notifications. Set your primary brand color
      using the color picker or by entering a hex code — this color is used for portal headers,
      buttons, and status badges. Save your brand settings. From this point, every portal you
      create for every client automatically uses your logo, name, and color. To verify the
      appearance, create a test project, share the portal link with yourself, and view it from
      a browser where you are not logged into ClientPortal (use an incognito window) — this
      is exactly what your clients see. If you manage multiple brands under one account, navigate
      to Workspaces, create a workspace for each brand, and configure independent brand settings
      per workspace. Assign each new project to the appropriate workspace during project creation.
    </p>
  </div>

  <div class='faq-item'>
    <h3>How do clients access the portal without an account?</h3>
    <p>
      Each project generates a unique portal URL. Share this URL with your client via email,
      text, or any messaging tool. When the client clicks the link, they land directly in the
      project portal — there is no registration page, no password setup, and no app download
      prompt. The portal is fully functional in any modern mobile or desktop browser. If you
      have set a PIN for the project, the client sees a PIN entry screen before the portal loads.
      Enter the PIN and access is granted for that browser session. The PIN prompt appears again
      in a new browser or after clearing cookies. For clients who need to share portal access
      with a colleague — for example, a marketing manager sharing with the CMO for a final
      approval — they can simply forward the portal URL. Each person who visits the URL sees
      the same project content. Track who submitted approvals by name from the approvals panel,
      where each person identifies themselves at the start of their portal session.
    </p>
  </div>

  <div class='faq-item'>
    <h3>How do I request approval on a deliverable?</h3>
    <p>
      Upload the deliverable file to the project's Files section. Once the upload is complete,
      open the file detail view and click 'Request Approval.' A panel opens where you can
      add an optional note to the client (for example, 'Please review the three logo concepts
      on pages 2-4 and let us know which direction you prefer'). Click Send Approval Request.
      The client receives a notification email with a direct link to the deliverable in their
      portal, along with your note. In the portal, the file displays an Approval Requested
      badge. The client clicks into the file, reviews the content using the in-portal preview
      (for PDF and image files), then clicks either Approve or Request Changes. If they request
      changes, they must enter a written comment before the request submits. You receive
      a notification with their comment immediately. Upload the revised version, navigate to
      the file, and send a new approval request. The approval history panel on the file shows
      the complete chain of requests, decisions, and comments in chronological order.
    </p>
  </div>

  <div class='faq-item'>
    <h3>How do I share files and track downloads?</h3>
    <p>
      Upload files to a project from the Files tab in the project dashboard. Click 'Upload Files,'
      select one or more files from your computer, assign a category label (Draft, Final, Reference,
      Contract), and click Upload. Files appear in the client portal Files section immediately
      after upload. Clients can preview image and PDF files directly in the portal without
      downloading, and download any file using the Download button. Every download is logged
      automatically: the timestamp, the file name, and the portal session identifier appear in
      the file's Download History panel in your agency dashboard. To review download activity
      across the entire project, go to the project's Activity Log, which shows all file views,
      downloads, approval actions, and messages in chronological order. If a client contacts you
      claiming they never received the final deliverables, the download log provides a
      timestamped record of every time the files were accessed.
    </p>
  </div>

  <div class='faq-item'>
    <h3>How do I connect invoicing to the portal?</h3>
    <p>
      Open the project and navigate to the Invoices tab. Click 'Add Invoice' and fill in the
      invoice number, amount, issue date, and due date. Optionally add a description of what
      the invoice covers and a link to the actual invoice document (either a PDF uploaded to
      the portal or an external link to your invoicing tool). Save the invoice — it appears
      immediately in the client portal's Invoices section with an Unpaid status badge. When
      payment is received, open the invoice in ClientPortal and click 'Mark as Paid.' The
      status updates to Paid with the payment date, and the client sees the updated status
      in their portal. If you use a separate invoicing tool like InvoiceAI or FreshBooks,
      paste the payment link for that invoice in the ClientPortal invoice entry — clients
      can click through to pay via your existing payment flow, and you mark the record paid
      in ClientPortal once your invoicing tool confirms the payment. This keeps the portal
      as the single client-facing view without requiring you to change your existing billing workflow.
    </p>
  </div>
</div>
`;
